---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../policies/acm/ensure-placement-toleration


components:
  ## include cluster specific details to override the policy with
  - ../../cluster

