---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../policies/ocp/operators/cert-manager


components:
  ## include cluster specific details to override the policy with
  - ../../cluster
  ## set hook on resources we don't want argo to actually sync
  - ../../../../kustomize-configs/argo-hook

