---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../policies/ocp/cluster-configs/cluster-proxy


components:
  ## include cluster specific details to override the policy with
  - ../../cluster

