---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-appset.yml

components:
  - ../base/

patches:
  - target:
      kind: ApplicationSet
    path: ./cluster-appset.yml
